Document: vibe2urbansim
Title: Debian vibe2urbansim Manual
Author: <insert document author here>
Abstract: This manual describes what vibe2urbansim is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vibe2urbansim/vibe2urbansim.sgml.gz

Format: postscript
Files: /usr/share/doc/vibe2urbansim/vibe2urbansim.ps.gz

Format: text
Files: /usr/share/doc/vibe2urbansim/vibe2urbansim.text.gz

Format: HTML
Index: /usr/share/doc/vibe2urbansim/html/index.html
Files: /usr/share/doc/vibe2urbansim/html/*.html
